version: '3.5'

services:
    mysql:
#        command: --default-authentication-plugin=mysql_native_password
        container_name: mysql
        dns: 10.3.1.4
        dns_search:
            - ${HOST_IP}
            - ubuntu.home
            - home
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_PASSWORD_FILE: /run/secrets/mysql.pwd
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root.pwd
            MYSQL_USER: ${CFG_USER:?}
            TZ: America/New_York
        hostname: mysql.s4.home
        image: ${DOCKER_REGISTRY:-s2.ubuntu.home:5000/}thirdparty/mysql:${MYSQL_VERSION:-5.7.23}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        networks:
            - nagios-net 
        ports:
            - "3306:3306"
        restart: unless-stopped
        secrets:
            - mysql.pwd
            - mysql_root.pwd
        volumes:
            - ./mysql/conf.d:/etc/mysql/conf.d
            - ./mysql/data:/var/lib/mysql
            - ./mysql/loader:/docker-entrypoint-initdb.d
            - ./mysql/log:/var/log


    nagios:
        container_name: nagios
        depends_on:
            - mysql
        dns: 10.3.1.4
        dns_search:
            - ubuntu.home
            - home
        environment:
            NAGIOS_PASS_FILE: /run/secrets/nagios.pwd
            NAGIOS_USER: ${CFG_USER:?}
            NGINX_LOG_ACCESS: 'syslog:server=10.3.1.15:514,tag=nginx_access json'
            NGINX_LOG_ERRORS: 'syslog:server=10.3.1.15:514,tag=nginx_error notice'
            NCONF_DBHOST: mysql
            NCONF_DBNAME: nconf
            NCONF_DBPASS_FILE: /run/secrets/mysql.pwd
            NCONF_DBUSER: ${CFG_USER:?}
            SUPERVISORD_PASS_FILE: /run/secrets/supervisord.pwd         
            SUPERVISORD_USER: ${CFG_USER:?}
#            DEBUG_TRACE: ${DEBUG_TRACE:-0}
#            NGINX_DEBUG: 1
#            NCONF_DEBUG_MODE: 1              # [0|1] 
#            NCONF_DEBUG_GENERATE: 5          # [1=ERROR|2=WARN|3=INFO|4=DEBUG|5=TRACE] 
#            PHP_LOGGING: 1
            PNP4NAGIOS_LOGLEVEL: 4
#            NAGIOS_GITHUB_CREDENTIALS_FILE: /run/secrets/github.credentials
#            NAGIOS_GITHUB_EMAIL: ${CFG_EMAIL:?}
#            NAGIOS_GITHUB_NAME: ${CFG_NAME:?}
#            NAGIOS_REPO: github.com/ballab1/DBMS-backup
        extra_hosts:
            - "docker-host:${HOST_IP:?}"
        hostname: nagios.s4.home
        image: ${DOCKER_REGISTRY:-s2.ubuntu.home:5000/}${CONTAINER_OS:-alpine}/nagios/${NAGIOS_VERSION:-4.4.6}:${CONTAINER_TAG:-021f6504cb9bf8dedb887b33ae90712f2d794c40fa66206620aa30cd1a91ccd0}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        networks:
            - nagios-net 
        ports:
            - "25:25"
            - "8001:80"
            - "9001:9001"
        restart: unless-stopped
        secrets:
            - github.credentials
            - mysql.pwd
            - nagios.pwd
            - supervisord.pwd
        volumes:
            - ./nagios/archives:/var/nagios/archives
            - ./nagios/config:/var/www/nconf/output
            - ./nagios/rrd:/var/nagios/perfdata
            - ./nagios/log:/var/log

    nginx:
        container_name: nginx
        depends_on:
            - nagios
            - phpmyadmin
        dns: 10.3.1.4
        dns_search:
            - ubuntu.home
            - home
        environment:
#            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            SUPERVISORD_PASS_FILE: /run/secrets/supervisord.pwd
            SUPERVISORD_USER: ${CFG_USER:?}
            NGINX_LOG_ACCESS: 'syslog:server=10.3.1.15:514,tag=nginx_access json'
            NGINX_LOG_ERRORS: 'syslog:server=10.3.1.15:514,tag=nginx_error notice'
            WEB_USER_ID: ${CFG_USER:?}
            WEB_USER_PASS_FILE: /run/secrets/web_user.pwd
#            NGINX_DEBUG: 1
#            PWD_PROTECTED: 'true'
        hostname: nginx.s4.home
        image: ${DOCKER_REGISTRY:-s2.ubuntu.home:5000/}${CONTAINER_OS:-alpine}/nginx-proxy/${NGINX_VERSION:-1.20.2}:${CONTAINER_TAG:-e3f23a3f029d9cbead1c8841a7d14584c314fcc2bffe5f429c7f4247cd6b34bd}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        networks:
            - nagios-net 
        ports:
            - "80:80"
            - "443:443"
            - "9005:9001"
        restart: unless-stopped
        secrets:
            - supervisord.pwd
            - web_user.pwd
            - server.crt
            - server.key
            - dhparam.pem
        volumes:
            - ./nginx/log:/var/log
            - ./www:/var/www
            - ./nginx/conf.d:/etc/nginx/proxy.conf

    phpmyadmin:
        container_name: phpmyadmin
        dns: 10.3.1.4
        dns_search:
            - ubuntu.home
            - home
        environment:
#            DEBUG_TRACE: ${DEBUG_TRACE:-0}
#            MYSQL_PASSWORD_FILE: /run/secrets/mysql.pwd
#            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root.pwd
#            MYSQL_USER: ${CFG_USER:?}
#            PMA_ABSOLUTE_URI: http://${HOST_IP:?}:8002/phpmyadmin
#            PMA_ARBITRARY: 1
            PMA_HOST: mysql
            PMA_PASSWORD_FILE: /run/secrets/pma.pwd
            PMA_PORT: 3306
            PMA_USER: ${CFG_USER:?}
            NGINX_LOG_ACCESS: 'syslog:server=10.3.1.15:514,tag=nginx_access logstash'
            NGINX_LOG_ERRORS: 'syslog:server=10.3.1.15:514,tag=nginx_error notice'
            SUPERVISORD_PASS_FILE: /run/secrets/supervisord.pwd
            SUPERVISORD_USER: ${CFG_USER:?}
            USER: www-data
#            NGINX_DEBUG: 1
#            PMA_VERBOSE: 1
        hostname: phpmyadmin.s4.home
        image: ${DOCKER_REGISTRY:-s2.ubuntu.home:5000/}${CONTAINER_OS:-alpine}/phpmyadmin/${PHPMYADMIN_VERSION:-5.1.1}:${CONTAINER_TAG:-63214692434495b882b166243c63bbc0b3e635f0cd6424b6ae58596b025cb577}
        links:
            - mysql:mysql
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        networks:
            - nagios-net 
        ports:
            - "8002:80"
            - "9102:9000"
            - "9002:9001"
        restart: unless-stopped
        secrets:
#            - mysql.pwd
#            - mysql_root.pwd
            - pma.pwd
            - supervisord.pwd
        volumes:
            - ./phpmyadmin/log:/var/log
#            - ./phpmyadmin/etc:/etc/phpmyadmin


networks:
   nagios-net:
       ipam:
           config:
               - subnet: 172.31.254.0/24
       name: nagios-container-net


secrets:
   github.credentials:
     file: .secrets/secrets/credentials.github
   mysql.pwd:
     file: .secrets/secrets/bobb.pwd
   mysql_root.pwd:
     file: .secrets/secrets/bobb.pwd
   nagios.pwd:
     file: .secrets/secrets/bobb.pwd
   pma.pwd:
     file: .secrets/secrets/bobb.pwd
#   github.token:
#     file: .secrets/secrets/hubot_token.github
   supervisord.pwd:      
     file: .secrets/secrets/bobb.pwd
   web_user.pwd:
     file: .secrets/secrets/bobb.pwd
   server.crt:
     file: .secrets/ssl/server.crt
   server.key:
     file: .secrets/ssl/server.key
   dhparam.pem:
     file: .secrets/ssl/dhparam.pem
